/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Vendedor;


import Modelo.SqlCategoria;
import Modelo.SqlCliente;
import Modelo.SqlEstado;
import Modelo.SqlFacturacion;
import Modelo.SqlMarca;
import Modelo.SqlProductos;
import Modelo.SqlProveedor;
import Modelo.SqlUsuarios;
import Modelo.categoria;
import Modelo.cliente;
import Modelo.facturacion;
import Modelo.marca;
import Modelo.productos;
import Modelo.proveedor;
import Modelo.usuarios;
import controlador.ctrlCategoria;
import controlador.ctrlCliente;
import controlador.ctrlClienteagg;
import controlador.ctrlFacturacion;
import controlador.ctrlMarca;
import controlador.ctrlProductos;
import controlador.ctrlProveedores;
import controlador.ctrlUsuarios;

/**
 *
 * @author DELL
 */
public class Menu extends javax.swing.JFrame {
public static Productos frproductos;
public static Facturacion frfacturacion;
public static Cliente frcliente;

public static BuscarCliente frcliente2;

public static Proveedor frproveedor;
public static RegistrarMarca frmarca;
public static Usuarios frusuarios;
public static Menu frmenu;
public static Registro frregistro;
public static IniciarSesion frlogin;
public static ctrlUsuarios ctr;
public static ctrlProveedores ctrpr;
public static ctrlProductos ctrp;
public static ctrlFacturacion ctrf;

public static ctrlCategoria ctrc;
public static ctrlMarca ctrm;
public static ctrlCliente ctrcli;

public static ctrlClienteagg ctrcli2;


SqlUsuarios usuario = new SqlUsuarios();
usuarios usu = new usuarios();

SqlFacturacion facturacion = new SqlFacturacion();
facturacion fact = new facturacion();
   
SqlProductos sqlpro= new SqlProductos();
productos pro = new productos();

SqlCategoria sqlcat= new SqlCategoria();
categoria cat=new categoria();

SqlMarca sqlmarca= new SqlMarca();
marca mar= new marca();

SqlProveedor sqlprov= new SqlProveedor();
proveedor prov= new proveedor();

SqlCliente sqlcliente= new SqlCliente();
cliente clie= new cliente();

//SqlEstado sqlest= new SqlEstado();
//estado est= new estado();

usuarios mod;   
    public Menu() {
        initComponents();
         setLocationRelativeTo(null);
         this.setExtendedState(MAXIMIZED_BOTH);
    }
   public Menu(usuarios mod){
       initComponents();
         setLocationRelativeTo(null);
         this.setExtendedState(MAXIMIZED_BOTH);
       this.mod=mod;
       
       if(mod.getId_tipo()==1){
       usuadm.setText(" Administrador: "+mod.getNombre());
       } else if (mod.getId_tipo()==2)
       {
           menuAdmi.setEnabled(false);
           usuadm.setText(" Usuario: "+mod.getNombre());
       }
   }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        BtnProductos = new javax.swing.JButton();
        btnProveedores = new javax.swing.JButton();
        btnFacturacion = new javax.swing.JButton();
        btnReportes = new javax.swing.JButton();
        btnMarca = new javax.swing.JButton();
        usuadm = new javax.swing.JLabel();
        BtnClientes = new javax.swing.JButton();
        btnUsuario = new javax.swing.JButton();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jMenu2 = new javax.swing.JMenu();
        menuAdmi = new javax.swing.JMenu();
        jMenuItem1 = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(33, 45, 62));

        BtnProductos.setBackground(new java.awt.Color(33, 45, 62));
        BtnProductos.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        BtnProductos.setForeground(new java.awt.Color(255, 255, 255));
        BtnProductos.setText("Productos");
        BtnProductos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnProductosActionPerformed(evt);
            }
        });

        btnProveedores.setBackground(new java.awt.Color(33, 45, 62));
        btnProveedores.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btnProveedores.setForeground(new java.awt.Color(255, 255, 255));
        btnProveedores.setText("Proveedores");
        btnProveedores.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnProveedoresActionPerformed(evt);
            }
        });

        btnFacturacion.setBackground(new java.awt.Color(33, 45, 62));
        btnFacturacion.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btnFacturacion.setForeground(new java.awt.Color(255, 255, 255));
        btnFacturacion.setText("Facturación");
        btnFacturacion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnFacturacionActionPerformed(evt);
            }
        });

        btnReportes.setBackground(new java.awt.Color(33, 45, 62));
        btnReportes.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btnReportes.setForeground(new java.awt.Color(255, 255, 255));
        btnReportes.setText("Reportes");

        btnMarca.setBackground(new java.awt.Color(33, 45, 62));
        btnMarca.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btnMarca.setForeground(new java.awt.Color(255, 255, 255));
        btnMarca.setText("Marcas");
        btnMarca.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnMarcaActionPerformed(evt);
            }
        });

        usuadm.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        usuadm.setForeground(new java.awt.Color(255, 255, 255));
        usuadm.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(33, 45, 62)));

        BtnClientes.setBackground(new java.awt.Color(33, 45, 62));
        BtnClientes.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        BtnClientes.setForeground(new java.awt.Color(255, 255, 255));
        BtnClientes.setText("Clientes");
        BtnClientes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnClientesActionPerformed(evt);
            }
        });

        btnUsuario.setBackground(new java.awt.Color(33, 45, 62));
        btnUsuario.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btnUsuario.setForeground(new java.awt.Color(255, 255, 255));
        btnUsuario.setText("Usuarios");
        btnUsuario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnUsuarioActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(BtnClientes, javax.swing.GroupLayout.PREFERRED_SIZE, 187, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(BtnProductos, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnProveedores, javax.swing.GroupLayout.DEFAULT_SIZE, 187, Short.MAX_VALUE)
                        .addComponent(btnFacturacion, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnReportes, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnMarca, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addComponent(usuadm, javax.swing.GroupLayout.PREFERRED_SIZE, 309, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnUsuario, javax.swing.GroupLayout.PREFERRED_SIZE, 187, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(831, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addComponent(BtnClientes, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(BtnProductos, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btnProveedores, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btnMarca, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btnFacturacion, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btnUsuario, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btnReportes, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 60, Short.MAX_VALUE)
                .addComponent(usuadm, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(14, 14, 14))
        );

        jMenuBar1.setBackground(new java.awt.Color(33, 45, 62));
        jMenuBar1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        jMenu1.setText("Sistema");
        jMenu1.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jMenuBar1.add(jMenu1);

        jMenu2.setText("Informaciones");
        jMenu2.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jMenuBar1.add(jMenu2);

        menuAdmi.setText("Administrador");
        menuAdmi.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N

        jMenuItem1.setText("Gestionar Usuarios");
        jMenuItem1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem1ActionPerformed(evt);
            }
        });
        menuAdmi.add(jMenuItem1);

        jMenuBar1.add(menuAdmi);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void BtnProductosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnProductosActionPerformed
        // TODO add your handling code here:
         if(frproductos == null){
       frproductos = new Productos(frmenu, true);
          ctrp= new ctrlProductos(pro, sqlpro, frproductos);
          ctrp.iniciar();
          
          ctrc= new ctrlCategoria(cat, sqlcat, frproductos);
          ctrc.iniciar();
          
          ctrm= new ctrlMarca(mar, sqlmarca, frproductos);
          ctrm.iniciar();
          
          
        frproductos.setVisible(true);
       
        }
        
        
    }//GEN-LAST:event_BtnProductosActionPerformed

    private void btnProveedoresActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnProveedoresActionPerformed
        // TODO add your handling code here:
         if(frproveedor == null){
             
             
           frproveedor = new Proveedor(frmenu, true);
          ctrpr= new ctrlProveedores(prov, sqlprov, frproveedor);
          ctrpr.iniciar();
        frproveedor.setVisible(true);
        }
    }//GEN-LAST:event_btnProveedoresActionPerformed

    private void btnMarcaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnMarcaActionPerformed
       if(frmarca == null){
           frmarca = new RegistrarMarca();
        frmarca.setVisible(true);
        }
       
    }//GEN-LAST:event_btnMarcaActionPerformed

    private void jMenuItem1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem1ActionPerformed
        // TODO add your handling code here:
        if(frusuarios == null){
         //  frusuarios = new Usuarios();
       // frusuarios.setVisible(true);
 
   frusuarios = new Usuarios(Menu.frmenu, true);
   ctr= new ctrlUsuarios(usu, usuario, frusuarios);

  ctr.iniciar();
frusuarios.setVisible(true);
        }
    }//GEN-LAST:event_jMenuItem1ActionPerformed

    private void btnFacturacionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnFacturacionActionPerformed
        // TODO add your handling code here:
        //sacar clie y fr cliente
           if(frfacturacion == null){
       frfacturacion = new Facturacion(frmenu, true);
          ctrf= new ctrlFacturacion(fact, facturacion, frfacturacion);
          ctrf.iniciar();
          
//          ctrf= new ctrlCategoria(cat, sqlcat, frproductos);
//          ctrc.iniciar();
//          
//          ctrm= new ctrlMarca(mar, sqlmarca, frproductos);
//          ctrm.iniciar();

        frfacturacion.setVisible(true);
        
        }
    }//GEN-LAST:event_btnFacturacionActionPerformed

    private void BtnClientesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnClientesActionPerformed
        // TODO add your handling code here:
        
          if(frcliente == null){
       frcliente = new Cliente(frmenu, true);
          ctrcli= new ctrlCliente(clie, sqlcliente, frcliente);
          ctrcli.iniciar();
          
//          ctrc= new ctrlCategoria(cat, sqlcat, frproductos);
//          ctrc.iniciar();
//          
//          ctrm= new ctrlMarca(mar, sqlmarca, frproductos);
//          ctrm.iniciar();
          
          
        frcliente.setVisible(true);
       
        }
    }//GEN-LAST:event_BtnClientesActionPerformed

    private void btnUsuarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnUsuarioActionPerformed
        // TODO add your handling code here:
            if(frusuarios == null){
         //  frusuarios = new Usuarios();
       // frusuarios.setVisible(true);
 
   frusuarios = new Usuarios(Menu.frmenu, true);
   ctr= new ctrlUsuarios(usu, usuario, frusuarios);

  ctr.iniciar();
frusuarios.setVisible(true);
        }
    }//GEN-LAST:event_btnUsuarioActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Menu().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BtnClientes;
    private javax.swing.JButton BtnProductos;
    private javax.swing.JButton btnFacturacion;
    private javax.swing.JButton btnMarca;
    private javax.swing.JButton btnProveedores;
    private javax.swing.JButton btnReportes;
    private javax.swing.JButton btnUsuario;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JMenu menuAdmi;
    private javax.swing.JLabel usuadm;
    // End of variables declaration//GEN-END:variables
}
