/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package Vista;

import Modelo.SqlCategoria;
import javax.swing.JDialog;
import javax.swing.JOptionPane;

/**
 *
 * @author DELL
 */
public class Productos extends JDialog {

    /**
     * Creates new form Productos
     */
    
    public Productos(Menu frmenu, boolean b) {
        super(frmenu, b);
        initComponents();
         setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel3 = new javax.swing.JPanel();
        jPanel1 = new javax.swing.JPanel();
        btnRegProducto = new javax.swing.JButton();
        btnMarca = new javax.swing.JButton();
        btnModificar = new javax.swing.JButton();
        btnEliminar = new javax.swing.JButton();
        btnCategoria = new javax.swing.JButton();
        btnBuscar = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        Pane_Prod = new javax.swing.JTabbedPane();
        P_buscar = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        txt_buscod = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        txt_busdesc = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        tabla_prod = new javax.swing.JTable();
        P_ges_c = new javax.swing.JPanel();
        jLabel24 = new javax.swing.JLabel();
        btnModificar_c = new javax.swing.JButton();
        jLabel25 = new javax.swing.JLabel();
        txt_buscar_c = new javax.swing.JTextField();
        combo_estado_c = new javax.swing.JComboBox<>();
        jLabel26 = new javax.swing.JLabel();
        btnGuardar_c = new javax.swing.JButton();
        txt_cod_c = new javax.swing.JTextField();
        jLabel27 = new javax.swing.JLabel();
        txt_desc_c = new javax.swing.JTextField();
        jScrollPane4 = new javax.swing.JScrollPane();
        tabla_categoria = new javax.swing.JTable();
        btnEliminar_c = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        P_ges_m = new javax.swing.JPanel();
        jLabel20 = new javax.swing.JLabel();
        jScrollPane3 = new javax.swing.JScrollPane();
        tabla_marca = new javax.swing.JTable();
        combo_estado_m = new javax.swing.JComboBox<>();
        txt_cod_m = new javax.swing.JTextField();
        txt_bus_m = new javax.swing.JTextField();
        jLabel21 = new javax.swing.JLabel();
        btnGuardar_m = new javax.swing.JButton();
        jLabel23 = new javax.swing.JLabel();
        txt_desc_m = new javax.swing.JTextField();
        btnModificar_m = new javax.swing.JButton();
        jLabel22 = new javax.swing.JLabel();
        btnEliminar_m = new javax.swing.JButton();
        P_reg_mod = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        txt_cod = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        combo_pro = new javax.swing.JComboBox<>();
        jLabel6 = new javax.swing.JLabel();
        txt_desc = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        combo_medida = new javax.swing.JComboBox<>();
        txt_descue = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        txt_iva = new javax.swing.JTextField();
        como_marca = new javax.swing.JComboBox<>();
        jLabel11 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        txt_obs = new javax.swing.JTextField();
        txt_stock = new javax.swing.JTextField();
        txt_venta = new javax.swing.JTextField();
        txt_mayo = new javax.swing.JTextField();
        txt_costo = new javax.swing.JTextField();
        jLabel12 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        combo_cate = new javax.swing.JComboBox<>();
        jLabel16 = new javax.swing.JLabel();
        txt_precio_cred = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosing(java.awt.event.WindowEvent evt) {
                formWindowClosing(evt);
            }
        });

        jPanel3.setBackground(new java.awt.Color(33, 45, 62));

        jPanel1.setBackground(new java.awt.Color(33, 45, 62));
        jPanel1.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        btnRegProducto.setBackground(new java.awt.Color(33, 45, 62));
        btnRegProducto.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btnRegProducto.setForeground(new java.awt.Color(255, 255, 255));
        btnRegProducto.setText("Registrar Producto");
        btnRegProducto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRegProductoActionPerformed(evt);
            }
        });

        btnMarca.setBackground(new java.awt.Color(33, 45, 62));
        btnMarca.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btnMarca.setForeground(new java.awt.Color(255, 255, 255));
        btnMarca.setText("Gestionar Marca");
        btnMarca.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnMarcaActionPerformed(evt);
            }
        });

        btnModificar.setBackground(new java.awt.Color(33, 45, 62));
        btnModificar.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btnModificar.setForeground(new java.awt.Color(255, 255, 255));
        btnModificar.setText("Modificar Producto");
        btnModificar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnModificarActionPerformed(evt);
            }
        });

        btnEliminar.setBackground(new java.awt.Color(33, 45, 62));
        btnEliminar.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btnEliminar.setForeground(new java.awt.Color(255, 255, 255));
        btnEliminar.setText("Eliminar Producto");
        btnEliminar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEliminarActionPerformed(evt);
            }
        });

        btnCategoria.setBackground(new java.awt.Color(33, 45, 62));
        btnCategoria.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btnCategoria.setForeground(new java.awt.Color(255, 255, 255));
        btnCategoria.setText("Gestionar Categoria");
        btnCategoria.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCategoriaActionPerformed(evt);
            }
        });

        btnBuscar.setBackground(new java.awt.Color(33, 45, 62));
        btnBuscar.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btnBuscar.setForeground(new java.awt.Color(255, 255, 255));
        btnBuscar.setText("Buscar Producto");
        btnBuscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBuscarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(btnRegProducto, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btnCategoria, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btnMarca, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btnEliminar, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btnModificar, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addComponent(btnBuscar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(btnBuscar, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btnRegProducto, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btnModificar, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btnEliminar, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btnCategoria, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btnMarca, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel2.setBackground(new java.awt.Color(33, 45, 62));
        jPanel2.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        Pane_Prod.setBackground(new java.awt.Color(33, 45, 62));
        Pane_Prod.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                Pane_ProdStateChanged(evt);
            }
        });
        Pane_Prod.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                Pane_ProdMouseClicked(evt);
            }
        });

        P_buscar.setBackground(new java.awt.Color(33, 45, 62));

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Buscar por código:");

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Buscar por descripcion:");

        tabla_prod.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {

            }
        ));
        jScrollPane1.setViewportView(tabla_prod);

        javax.swing.GroupLayout P_buscarLayout = new javax.swing.GroupLayout(P_buscar);
        P_buscar.setLayout(P_buscarLayout);
        P_buscarLayout.setHorizontalGroup(
            P_buscarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(P_buscarLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(P_buscarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1)
                    .addGroup(P_buscarLayout.createSequentialGroup()
                        .addGroup(P_buscarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txt_buscod, javax.swing.GroupLayout.PREFERRED_SIZE, 152, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 123, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(P_buscarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2)
                            .addComponent(txt_busdesc, javax.swing.GroupLayout.PREFERRED_SIZE, 364, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(0, 226, Short.MAX_VALUE)))
                .addContainerGap())
        );
        P_buscarLayout.setVerticalGroup(
            P_buscarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(P_buscarLayout.createSequentialGroup()
                .addGap(17, 17, 17)
                .addGroup(P_buscarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jLabel2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(P_buscarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txt_buscod, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txt_busdesc, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 357, Short.MAX_VALUE)
                .addContainerGap())
        );

        Pane_Prod.addTab("Buscar", P_buscar);

        P_ges_c.setBackground(new java.awt.Color(33, 45, 62));

        jLabel24.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel24.setForeground(new java.awt.Color(255, 255, 255));
        jLabel24.setText("Código:");

        btnModificar_c.setBackground(new java.awt.Color(33, 45, 62));
        btnModificar_c.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        btnModificar_c.setForeground(new java.awt.Color(255, 255, 255));
        btnModificar_c.setText("Modificar");
        btnModificar_c.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnModificar_cActionPerformed(evt);
            }
        });

        jLabel25.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel25.setForeground(new java.awt.Color(255, 255, 255));
        jLabel25.setText("Buscar:");

        txt_buscar_c.setMinimumSize(new java.awt.Dimension(6, 25));
        txt_buscar_c.setPreferredSize(new java.awt.Dimension(6, 25));
        txt_buscar_c.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_buscar_cActionPerformed(evt);
            }
        });

        combo_estado_c.setBackground(new java.awt.Color(33, 45, 62));
        combo_estado_c.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        combo_estado_c.setForeground(new java.awt.Color(255, 255, 255));
        combo_estado_c.setMinimumSize(new java.awt.Dimension(67, 25));
        combo_estado_c.setPreferredSize(new java.awt.Dimension(67, 25));

        jLabel26.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel26.setForeground(new java.awt.Color(255, 255, 255));
        jLabel26.setText("Descripción:");

        btnGuardar_c.setBackground(new java.awt.Color(33, 45, 62));
        btnGuardar_c.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        btnGuardar_c.setForeground(new java.awt.Color(255, 255, 255));
        btnGuardar_c.setText("Guardar");
        btnGuardar_c.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGuardar_cActionPerformed(evt);
            }
        });

        txt_cod_c.setMinimumSize(new java.awt.Dimension(6, 25));
        txt_cod_c.setPreferredSize(new java.awt.Dimension(6, 25));
        txt_cod_c.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_cod_cActionPerformed(evt);
            }
        });

        jLabel27.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel27.setForeground(new java.awt.Color(255, 255, 255));
        jLabel27.setText("Estado:");

        txt_desc_c.setMinimumSize(new java.awt.Dimension(6, 25));
        txt_desc_c.setPreferredSize(new java.awt.Dimension(6, 25));
        txt_desc_c.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_desc_cActionPerformed(evt);
            }
        });

        tabla_categoria.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {

            }
        ));
        tabla_categoria.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tabla_categoriaMouseClicked(evt);
            }
        });
        jScrollPane4.setViewportView(tabla_categoria);

        btnEliminar_c.setBackground(new java.awt.Color(33, 45, 62));
        btnEliminar_c.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        btnEliminar_c.setForeground(new java.awt.Color(255, 255, 255));
        btnEliminar_c.setText("Eliminar");
        btnEliminar_c.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEliminar_cActionPerformed(evt);
            }
        });

        jButton1.setText("buscar");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout P_ges_cLayout = new javax.swing.GroupLayout(P_ges_c);
        P_ges_c.setLayout(P_ges_cLayout);
        P_ges_cLayout.setHorizontalGroup(
            P_ges_cLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(P_ges_cLayout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addGroup(P_ges_cLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnGuardar_c, javax.swing.GroupLayout.PREFERRED_SIZE, 303, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel24)
                    .addGroup(P_ges_cLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(jLabel26)
                        .addGroup(P_ges_cLayout.createSequentialGroup()
                            .addComponent(txt_cod_c, javax.swing.GroupLayout.PREFERRED_SIZE, 119, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(18, 18, 18)
                            .addGroup(P_ges_cLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jLabel27)
                                .addComponent(combo_estado_c, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                        .addComponent(txt_desc_c, javax.swing.GroupLayout.PREFERRED_SIZE, 303, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(btnModificar_c, javax.swing.GroupLayout.PREFERRED_SIZE, 303, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnEliminar_c, javax.swing.GroupLayout.PREFERRED_SIZE, 303, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(50, 50, 50)
                .addGroup(P_ges_cLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(P_ges_cLayout.createSequentialGroup()
                        .addComponent(jLabel25)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txt_buscar_c, javax.swing.GroupLayout.PREFERRED_SIZE, 217, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jButton1))
                    .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 367, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(23, Short.MAX_VALUE))
        );
        P_ges_cLayout.setVerticalGroup(
            P_ges_cLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(P_ges_cLayout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(P_ges_cLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel24)
                    .addComponent(jLabel27)
                    .addComponent(jLabel25)
                    .addComponent(txt_buscar_c, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(P_ges_cLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(P_ges_cLayout.createSequentialGroup()
                        .addGroup(P_ges_cLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txt_cod_c, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(combo_estado_c, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addComponent(jLabel26)
                        .addGap(18, 18, 18)
                        .addComponent(txt_desc_c, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(58, 58, 58)
                        .addComponent(btnGuardar_c, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btnModificar_c, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(12, 12, 12)
                        .addComponent(btnEliminar_c, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 355, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(24, Short.MAX_VALUE))
        );

        Pane_Prod.addTab("Gestionar Categoria", P_ges_c);

        P_ges_m.setBackground(new java.awt.Color(33, 45, 62));

        jLabel20.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel20.setForeground(new java.awt.Color(255, 255, 255));
        jLabel20.setText("Código:");

        tabla_marca.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {

            }
        ));
        tabla_marca.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tabla_marcaMouseClicked(evt);
            }
        });
        jScrollPane3.setViewportView(tabla_marca);

        combo_estado_m.setBackground(new java.awt.Color(33, 45, 62));
        combo_estado_m.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        combo_estado_m.setForeground(new java.awt.Color(255, 255, 255));
        combo_estado_m.setMinimumSize(new java.awt.Dimension(67, 25));
        combo_estado_m.setPreferredSize(new java.awt.Dimension(67, 25));

        txt_cod_m.setMinimumSize(new java.awt.Dimension(6, 25));
        txt_cod_m.setPreferredSize(new java.awt.Dimension(6, 25));
        txt_cod_m.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_cod_mActionPerformed(evt);
            }
        });

        txt_bus_m.setMinimumSize(new java.awt.Dimension(6, 25));
        txt_bus_m.setPreferredSize(new java.awt.Dimension(6, 25));
        txt_bus_m.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_bus_mActionPerformed(evt);
            }
        });

        jLabel21.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel21.setForeground(new java.awt.Color(255, 255, 255));
        jLabel21.setText("Descripción:");

        btnGuardar_m.setBackground(new java.awt.Color(33, 45, 62));
        btnGuardar_m.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        btnGuardar_m.setForeground(new java.awt.Color(255, 255, 255));
        btnGuardar_m.setText("Guardar");
        btnGuardar_m.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGuardar_mActionPerformed(evt);
            }
        });

        jLabel23.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel23.setForeground(new java.awt.Color(255, 255, 255));
        jLabel23.setText("Buscar:");

        txt_desc_m.setMinimumSize(new java.awt.Dimension(6, 25));
        txt_desc_m.setPreferredSize(new java.awt.Dimension(6, 25));
        txt_desc_m.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_desc_mActionPerformed(evt);
            }
        });

        btnModificar_m.setBackground(new java.awt.Color(33, 45, 62));
        btnModificar_m.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        btnModificar_m.setForeground(new java.awt.Color(255, 255, 255));
        btnModificar_m.setText("Modificar");
        btnModificar_m.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnModificar_mActionPerformed(evt);
            }
        });

        jLabel22.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel22.setForeground(new java.awt.Color(255, 255, 255));
        jLabel22.setText("Estado:");

        btnEliminar_m.setBackground(new java.awt.Color(33, 45, 62));
        btnEliminar_m.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        btnEliminar_m.setForeground(new java.awt.Color(255, 255, 255));
        btnEliminar_m.setText("Eliminar");
        btnEliminar_m.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEliminar_mActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout P_ges_mLayout = new javax.swing.GroupLayout(P_ges_m);
        P_ges_m.setLayout(P_ges_mLayout);
        P_ges_mLayout.setHorizontalGroup(
            P_ges_mLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(P_ges_mLayout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addGroup(P_ges_mLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnGuardar_m, javax.swing.GroupLayout.PREFERRED_SIZE, 303, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel20)
                    .addGroup(P_ges_mLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(jLabel21)
                        .addGroup(P_ges_mLayout.createSequentialGroup()
                            .addComponent(txt_cod_m, javax.swing.GroupLayout.PREFERRED_SIZE, 119, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(18, 18, 18)
                            .addGroup(P_ges_mLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jLabel22)
                                .addComponent(combo_estado_m, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                        .addComponent(txt_desc_m, javax.swing.GroupLayout.PREFERRED_SIZE, 303, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(btnModificar_m, javax.swing.GroupLayout.PREFERRED_SIZE, 303, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnEliminar_m, javax.swing.GroupLayout.PREFERRED_SIZE, 303, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(50, 50, 50)
                .addGroup(P_ges_mLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(P_ges_mLayout.createSequentialGroup()
                        .addComponent(jLabel23)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txt_bus_m, javax.swing.GroupLayout.PREFERRED_SIZE, 217, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 367, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(26, Short.MAX_VALUE))
        );
        P_ges_mLayout.setVerticalGroup(
            P_ges_mLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(P_ges_mLayout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addGroup(P_ges_mLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel20)
                    .addComponent(jLabel22)
                    .addComponent(jLabel23)
                    .addComponent(txt_bus_m, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(P_ges_mLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(P_ges_mLayout.createSequentialGroup()
                        .addGroup(P_ges_mLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(P_ges_mLayout.createSequentialGroup()
                                .addGap(2, 2, 2)
                                .addComponent(txt_cod_m, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(combo_estado_m, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addComponent(jLabel21)
                        .addGap(18, 18, 18)
                        .addComponent(txt_desc_m, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(58, 58, 58)
                        .addComponent(btnGuardar_m, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btnModificar_m, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(12, 12, 12)
                        .addComponent(btnEliminar_m, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 355, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(27, 27, 27))
        );

        Pane_Prod.addTab("Gestionar marca", P_ges_m);

        P_reg_mod.setBackground(new java.awt.Color(33, 45, 62));

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Código:");

        txt_cod.setMinimumSize(new java.awt.Dimension(6, 25));
        txt_cod.setPreferredSize(new java.awt.Dimension(6, 25));
        txt_cod.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_codActionPerformed(evt);
            }
        });

        jLabel7.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setText("Precio de costo:");

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("Proveedor:");

        combo_pro.setBackground(new java.awt.Color(33, 45, 62));
        combo_pro.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        combo_pro.setForeground(new java.awt.Color(255, 255, 255));
        combo_pro.setMinimumSize(new java.awt.Dimension(67, 25));
        combo_pro.setPreferredSize(new java.awt.Dimension(67, 25));
        combo_pro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                combo_proActionPerformed(evt);
            }
        });

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("Precio de venta:");

        txt_desc.setMinimumSize(new java.awt.Dimension(6, 25));
        txt_desc.setPreferredSize(new java.awt.Dimension(6, 25));
        txt_desc.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_descActionPerformed(evt);
            }
        });

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Descripción:");

        jLabel13.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel13.setForeground(new java.awt.Color(255, 255, 255));
        jLabel13.setText("Descuento:");

        jLabel8.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(255, 255, 255));
        jLabel8.setText("I.V.A:");

        combo_medida.setBackground(new java.awt.Color(33, 45, 62));
        combo_medida.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        combo_medida.setForeground(new java.awt.Color(255, 255, 255));
        combo_medida.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Seleccione una opción", "Unidad", "Metro", "Kg", "Caja", "Mt2" }));
        combo_medida.setMinimumSize(new java.awt.Dimension(67, 25));
        combo_medida.setPreferredSize(new java.awt.Dimension(67, 25));
        combo_medida.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                combo_medidaActionPerformed(evt);
            }
        });

        txt_descue.setMinimumSize(new java.awt.Dimension(6, 25));
        txt_descue.setPreferredSize(new java.awt.Dimension(6, 25));
        txt_descue.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_descueActionPerformed(evt);
            }
        });

        jLabel9.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(255, 255, 255));
        jLabel9.setText("Stock:");

        jLabel14.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel14.setForeground(new java.awt.Color(255, 255, 255));
        jLabel14.setText("Marca:");

        txt_iva.setMinimumSize(new java.awt.Dimension(6, 25));
        txt_iva.setPreferredSize(new java.awt.Dimension(6, 25));
        txt_iva.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_ivaActionPerformed(evt);
            }
        });

        como_marca.setBackground(new java.awt.Color(33, 45, 62));
        como_marca.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        como_marca.setForeground(new java.awt.Color(255, 255, 255));
        como_marca.setToolTipText("");
        como_marca.setMinimumSize(new java.awt.Dimension(67, 25));
        como_marca.setPreferredSize(new java.awt.Dimension(67, 25));
        como_marca.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                como_marcaActionPerformed(evt);
            }
        });

        jLabel11.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(255, 255, 255));
        jLabel11.setText("Unidad de medida:");

        jLabel10.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(255, 255, 255));
        jLabel10.setText("Observación:");

        txt_obs.setMinimumSize(new java.awt.Dimension(6, 25));
        txt_obs.setPreferredSize(new java.awt.Dimension(6, 25));
        txt_obs.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_obsActionPerformed(evt);
            }
        });

        txt_stock.setMinimumSize(new java.awt.Dimension(6, 25));
        txt_stock.setPreferredSize(new java.awt.Dimension(6, 25));
        txt_stock.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_stockActionPerformed(evt);
            }
        });

        txt_venta.setMinimumSize(new java.awt.Dimension(6, 25));
        txt_venta.setPreferredSize(new java.awt.Dimension(6, 25));
        txt_venta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_ventaActionPerformed(evt);
            }
        });

        txt_mayo.setMinimumSize(new java.awt.Dimension(6, 25));
        txt_mayo.setPreferredSize(new java.awt.Dimension(6, 25));
        txt_mayo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_mayoActionPerformed(evt);
            }
        });

        txt_costo.setMinimumSize(new java.awt.Dimension(6, 25));
        txt_costo.setPreferredSize(new java.awt.Dimension(6, 25));
        txt_costo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_costoActionPerformed(evt);
            }
        });
        txt_costo.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txt_costoKeyTyped(evt);
            }
        });

        jLabel12.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(255, 255, 255));
        jLabel12.setText("Precio mayorista:");

        jLabel15.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel15.setForeground(new java.awt.Color(255, 255, 255));
        jLabel15.setText("Categoria:");

        combo_cate.setBackground(new java.awt.Color(33, 45, 62));
        combo_cate.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        combo_cate.setForeground(new java.awt.Color(255, 255, 255));
        combo_cate.setToolTipText("");
        combo_cate.setMinimumSize(new java.awt.Dimension(67, 25));
        combo_cate.setPreferredSize(new java.awt.Dimension(67, 25));
        combo_cate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                combo_cateActionPerformed(evt);
            }
        });

        jLabel16.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel16.setForeground(new java.awt.Color(255, 255, 255));
        jLabel16.setText("Precio a credito:");

        javax.swing.GroupLayout P_reg_modLayout = new javax.swing.GroupLayout(P_reg_mod);
        P_reg_mod.setLayout(P_reg_modLayout);
        P_reg_modLayout.setHorizontalGroup(
            P_reg_modLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(P_reg_modLayout.createSequentialGroup()
                .addGap(11, 11, 11)
                .addGroup(P_reg_modLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel4)
                    .addComponent(jLabel3)
                    .addComponent(jLabel5)
                    .addComponent(jLabel7)
                    .addComponent(jLabel6)
                    .addComponent(jLabel12)
                    .addComponent(jLabel16))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(P_reg_modLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(txt_precio_cred, javax.swing.GroupLayout.DEFAULT_SIZE, 217, Short.MAX_VALUE)
                    .addComponent(txt_mayo, javax.swing.GroupLayout.DEFAULT_SIZE, 217, Short.MAX_VALUE)
                    .addComponent(txt_desc, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(txt_cod, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(combo_pro, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(txt_venta, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(txt_costo, javax.swing.GroupLayout.DEFAULT_SIZE, 217, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 7, Short.MAX_VALUE)
                .addGroup(P_reg_modLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel14, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel13, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel11, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel8, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel9, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel15, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel10, javax.swing.GroupLayout.Alignment.TRAILING))
                .addGap(18, 47, Short.MAX_VALUE)
                .addGroup(P_reg_modLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(txt_obs, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(como_marca, 0, 217, Short.MAX_VALUE)
                    .addComponent(txt_descue, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(combo_medida, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(txt_iva, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(txt_stock, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(combo_cate, 0, 217, Short.MAX_VALUE))
                .addGap(14, 14, 14))
        );
        P_reg_modLayout.setVerticalGroup(
            P_reg_modLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(P_reg_modLayout.createSequentialGroup()
                .addGroup(P_reg_modLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(P_reg_modLayout.createSequentialGroup()
                        .addGroup(P_reg_modLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel14)
                            .addComponent(como_marca, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(P_reg_modLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(txt_descue, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel13))
                        .addGap(18, 18, 18)
                        .addGroup(P_reg_modLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(combo_medida, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, 15, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(P_reg_modLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txt_iva, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel8))
                        .addGap(20, 20, 20)
                        .addGroup(P_reg_modLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(txt_stock, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel9))
                        .addGap(18, 18, 18)
                        .addGroup(P_reg_modLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel15)
                            .addComponent(combo_cate, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(P_reg_modLayout.createSequentialGroup()
                        .addGroup(P_reg_modLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(P_reg_modLayout.createSequentialGroup()
                                .addGap(74, 74, 74)
                                .addComponent(jLabel3))
                            .addGroup(P_reg_modLayout.createSequentialGroup()
                                .addGap(71, 71, 71)
                                .addComponent(txt_cod, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(17, 17, 17)
                        .addGroup(P_reg_modLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel4)
                            .addComponent(txt_desc, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(P_reg_modLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(combo_pro, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel5))
                        .addGap(23, 23, 23)
                        .addGroup(P_reg_modLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txt_costo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel7))
                        .addGap(18, 18, 18)
                        .addGroup(P_reg_modLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(txt_venta, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel6))
                        .addGap(18, 18, 18)
                        .addGroup(P_reg_modLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(txt_mayo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel12))))
                .addGap(18, 18, 18)
                .addGroup(P_reg_modLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(P_reg_modLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(txt_obs, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel10))
                    .addGroup(P_reg_modLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel16)
                        .addComponent(txt_precio_cred, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(83, Short.MAX_VALUE))
        );

        Pane_Prod.addTab("Registrar/Modificar", P_reg_mod);

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(Pane_Prod)
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(Pane_Prod)
                .addContainerGap())
        );

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnRegProductoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRegProductoActionPerformed
        // TODO add your handling code here:
      
    }//GEN-LAST:event_btnRegProductoActionPerformed

    private void btnMarcaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnMarcaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnMarcaActionPerformed

    private void btnCategoriaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCategoriaActionPerformed
       
    }//GEN-LAST:event_btnCategoriaActionPerformed

    private void btnModificarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnModificarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnModificarActionPerformed

    private void formWindowClosing(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosing
        // TODO add your handling code here:
        Menu.frproductos=null;
    }//GEN-LAST:event_formWindowClosing

    private void btnEliminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEliminarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnEliminarActionPerformed

    private void txt_codActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_codActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_codActionPerformed

    private void txt_descActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_descActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_descActionPerformed

    private void txt_ventaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_ventaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_ventaActionPerformed

    private void txt_mayoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_mayoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_mayoActionPerformed

    private void txt_costoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_costoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_costoActionPerformed

    private void combo_proActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_combo_proActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_combo_proActionPerformed

    private void txt_ivaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_ivaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_ivaActionPerformed

    private void combo_medidaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_combo_medidaActionPerformed

    }//GEN-LAST:event_combo_medidaActionPerformed

    private void txt_stockActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_stockActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_stockActionPerformed

    private void como_marcaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_como_marcaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_como_marcaActionPerformed

    private void txt_descueActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_descueActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_descueActionPerformed

    private void txt_obsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_obsActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_obsActionPerformed

    private void combo_cateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_combo_cateActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_combo_cateActionPerformed

    private void txt_cod_mActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_cod_mActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_cod_mActionPerformed

    private void txt_desc_mActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_desc_mActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_desc_mActionPerformed

    private void txt_bus_mActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_bus_mActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_bus_mActionPerformed

    private void tabla_marcaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tabla_marcaMouseClicked
        // TODO add your handling code here:
      
    }//GEN-LAST:event_tabla_marcaMouseClicked

    private void btnGuardar_mActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGuardar_mActionPerformed
        // TODO add your handling code here:
       
    }//GEN-LAST:event_btnGuardar_mActionPerformed

    private void btnModificar_mActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnModificar_mActionPerformed
        // TODO add your handling code here:
     
    }//GEN-LAST:event_btnModificar_mActionPerformed

    private void btnEliminar_mActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEliminar_mActionPerformed

    }//GEN-LAST:event_btnEliminar_mActionPerformed

    private void btnModificar_cActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnModificar_cActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnModificar_cActionPerformed

    private void txt_buscar_cActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_buscar_cActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_buscar_cActionPerformed

    private void btnGuardar_cActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGuardar_cActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnGuardar_cActionPerformed

    private void txt_cod_cActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_cod_cActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_cod_cActionPerformed

    private void txt_desc_cActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_desc_cActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_desc_cActionPerformed

    private void tabla_categoriaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tabla_categoriaMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_tabla_categoriaMouseClicked

    private void btnEliminar_cActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEliminar_cActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnEliminar_cActionPerformed

    private void Pane_ProdStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_Pane_ProdStateChanged
        // TODO add your handling code here:
//  if(evt.getSource()== Pane_Prod){
//if(this.Pane_Prod.getSelectedIndex()==0 ||this.Pane_Prod.getSelectedIndex()==2 || this.Pane_Prod.getSelectedIndex()==3){
//
//}else{
//JOptionPane.showMessageDialog(null,"registro");
//}
////  limpiar();
//  
//      }
    }//GEN-LAST:event_Pane_ProdStateChanged

    
    private void Pane_ProdMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Pane_ProdMouseClicked
        // TODO add your handling code here:
      //  if(evt.getSource()== P_reg_mod){
//   //     if(this.frpro.jTabbedPane1.getSelectedIndex()==0 ||this.frpro.jTabbedPane1.getSelectedIndex()==2 || this.frpro.jTabbedPane1.getSelectedIndex()==3){
//  //      }
//  limpiar();
  //JOptionPane.showMessageDialog(null,"impecil");
   //     }
        
        
    }//GEN-LAST:event_Pane_ProdMouseClicked

    private void btnBuscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBuscarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnBuscarActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
          SqlCategoria.mostrarCategoria(txt_buscar_c.getText());
    }//GEN-LAST:event_jButton1ActionPerformed

    private void txt_costoKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txt_costoKeyTyped
        // TODO add your handling code here:
        
        
        
    }//GEN-LAST:event_txt_costoKeyTyped

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Productos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Productos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Productos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Productos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
//        java.awt.EventQueue.invokeLater(new Runnable() {
//            public void run() {
//                new Productos().setVisible(true);
//            }
//        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JPanel P_buscar;
    public javax.swing.JPanel P_ges_c;
    public javax.swing.JPanel P_ges_m;
    public javax.swing.JPanel P_reg_mod;
    public javax.swing.JTabbedPane Pane_Prod;
    public javax.swing.JButton btnBuscar;
    public javax.swing.JButton btnCategoria;
    public javax.swing.JButton btnEliminar;
    public javax.swing.JButton btnEliminar_c;
    public javax.swing.JButton btnEliminar_m;
    public javax.swing.JButton btnGuardar_c;
    public javax.swing.JButton btnGuardar_m;
    public javax.swing.JButton btnMarca;
    public javax.swing.JButton btnModificar;
    public javax.swing.JButton btnModificar_c;
    public javax.swing.JButton btnModificar_m;
    public javax.swing.JButton btnRegProducto;
    public javax.swing.JComboBox<String> combo_cate;
    public javax.swing.JComboBox<String> combo_estado_c;
    public javax.swing.JComboBox<String> combo_estado_m;
    public javax.swing.JComboBox<String> combo_medida;
    public javax.swing.JComboBox<String> combo_pro;
    public javax.swing.JComboBox<String> como_marca;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel27;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    public static javax.swing.JTable tabla_categoria;
    public static javax.swing.JTable tabla_marca;
    public static javax.swing.JTable tabla_prod;
    public javax.swing.JTextField txt_bus_m;
    public javax.swing.JTextField txt_buscar_c;
    public javax.swing.JTextField txt_buscod;
    public javax.swing.JTextField txt_busdesc;
    public javax.swing.JTextField txt_cod;
    public javax.swing.JTextField txt_cod_c;
    public javax.swing.JTextField txt_cod_m;
    public javax.swing.JTextField txt_costo;
    public javax.swing.JTextField txt_desc;
    public javax.swing.JTextField txt_desc_c;
    public javax.swing.JTextField txt_desc_m;
    public javax.swing.JTextField txt_descue;
    public javax.swing.JTextField txt_iva;
    public javax.swing.JTextField txt_mayo;
    public javax.swing.JTextField txt_obs;
    public javax.swing.JTextField txt_precio_cred;
    public javax.swing.JTextField txt_stock;
    public javax.swing.JTextField txt_venta;
    // End of variables declaration//GEN-END:variables
}
