/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Interfaz;

import Modelo.SqlProveedor;
import Modelo.proveedor;
import java.awt.HeadlessException;
import java.util.List;
import javax.swing.JOptionPane;
import javax.swing.JTable;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableColumnModel;

/**
 *
 * @author DELL
 */
public final class Proveedor extends javax.swing.JFrame {

  public static RegistrarProveedor frproveedor;
  public static ModificarProveedor frmodificarprov;
     
       
    public Proveedor() {
        initComponents();
         setLocationRelativeTo(null);
         tablaProveedor();
       //  cargar("");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        btnRegProd = new javax.swing.JButton();
        btnEliminarProv = new javax.swing.JButton();
        btnModificarProv = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        txt_busdesc = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        tabla_prov = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setBackground(new java.awt.Color(33, 45, 62));
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosing(java.awt.event.WindowEvent evt) {
                formWindowClosing(evt);
            }
        });

        jPanel1.setBackground(new java.awt.Color(33, 45, 62));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btnRegProd.setBackground(new java.awt.Color(33, 45, 62));
        btnRegProd.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btnRegProd.setForeground(new java.awt.Color(255, 255, 255));
        btnRegProd.setText("Registrar Proveedor");
        btnRegProd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRegProdActionPerformed(evt);
            }
        });
        jPanel1.add(btnRegProd, new org.netbeans.lib.awtextra.AbsoluteConstraints(21, 24, -1, 56));

        btnEliminarProv.setBackground(new java.awt.Color(33, 45, 62));
        btnEliminarProv.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btnEliminarProv.setForeground(new java.awt.Color(255, 255, 255));
        btnEliminarProv.setText("Eliminar ");
        btnEliminarProv.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEliminarProvActionPerformed(evt);
            }
        });
        jPanel1.add(btnEliminarProv, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 220, 162, 56));

        btnModificarProv.setBackground(new java.awt.Color(33, 45, 62));
        btnModificarProv.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btnModificarProv.setForeground(new java.awt.Color(255, 255, 255));
        btnModificarProv.setText("Modificar");
        btnModificarProv.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnModificarProvActionPerformed(evt);
            }
        });
        jPanel1.add(btnModificarProv, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 120, 161, 56));

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Buscar proveedor:");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 31, -1, -1));
        jPanel1.add(txt_busdesc, new org.netbeans.lib.awtextra.AbsoluteConstraints(323, 26, 268, -1));

        tabla_prov.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {

            }
        ));
        tabla_prov.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tabla_provMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tabla_prov);

        jPanel1.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 60, 610, 440));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 887, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 6, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnRegProdActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRegProdActionPerformed
        // TODO add your handling code here:
        
        if(frproveedor==null){
        frproveedor = new RegistrarProveedor();
        frproveedor.setVisible(true);
        }
    }//GEN-LAST:event_btnRegProdActionPerformed

    private void btnEliminarProvActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEliminarProvActionPerformed

          SqlProveedor prov = new SqlProveedor();
       proveedor p = new proveedor();
        int fila = tabla_prov.getSelectedRow();
        int id = (int) tabla_prov.getValueAt(fila, 0);
        DefaultTableModel tabla= new DefaultTableModel();
        
        try{
            if(fila<0){
                
            JOptionPane.showMessageDialog(this, "Seleccione alguna fila");
           
            }else {
           p.setId_prov(id);
           if(JOptionPane.showConfirmDialog(this, "¿Eliminar registro?", "", JOptionPane.OK_CANCEL_OPTION)==JOptionPane.OK_OPTION){
         
            if(prov.eliminarUsuario(p)){
            JOptionPane.showMessageDialog(null, "Eliminado correctamente","Información", JOptionPane.OK_OPTION);
            tablaProveedor();
            tabla.removeRow(id);
           }else{
                JOptionPane.showMessageDialog(this, "Error al eliminar", "Información", JOptionPane.OK_CANCEL_OPTION);}
                }
            }
            JOptionPane.showMessageDialog(null, "Error al eliminar");
           
           }catch(HeadlessException e){
           JOptionPane.showMessageDialog(null, e);
        
        }
    }//GEN-LAST:event_btnEliminarProvActionPerformed

    private void btnModificarProvActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnModificarProvActionPerformed
    if(frmodificarprov== null){
       frmodificarprov= new ModificarProveedor();
     //  selectTablaprov();
       frmodificarprov.setVisible(true);
    }
   
    
    }//GEN-LAST:event_btnModificarProvActionPerformed

    private void formWindowClosing(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosing
        // TODO add your handliang code here:
        RegistrarProveedor.frregistrarprov=null;
        ModificarProveedor.frmodificarprov=null;
    }//GEN-LAST:event_formWindowClosing

    private void tabla_provMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tabla_provMouseClicked
     
    }//GEN-LAST:event_tabla_provMouseClicked
    
 
    
    public void tablaProveedor(){
     
           SqlProveedor prov = new SqlProveedor();
       proveedor p = new proveedor();
    String [] columnas ={"CODIGO","PROVEEDOR","EMAIL", "CONTACTO"};
    Object[] obj= new Object[4];
    DefaultTableModel Tabla = new DefaultTableModel(null, columnas);
    List ls;
    try{
    ls= prov.mostrarProveedores();
    for (int i=0;i<ls.size(); i++){
        p = (proveedor) ls.get(i);
        obj[0] = p.getId_prov();
        obj[1] = p.getNombre_prov();
        obj[2] = p.getEmail(); 
        obj[3] = p.getContacto(); 
        Tabla.addRow(obj);
    }
    tabla_prov.setModel(Tabla);
   }catch (Exception e){
 //  e.printStackTrace();
   System.out.println(e);
   }
    
     tabla_prov.setAutoResizeMode(JTable.AUTO_RESIZE_OFF);
         TableColumnModel columnModel = tabla_prov.getColumnModel();
         columnModel.getColumn(0).setPreferredWidth(80);
         columnModel.getColumn(1).setPreferredWidth(150);
         columnModel.getColumn(2).setPreferredWidth(200);
         columnModel.getColumn(3).setPreferredWidth(200);
    }
    
    
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Proveedor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Proveedor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Proveedor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Proveedor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Proveedor().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnEliminarProv;
    private javax.swing.JButton btnModificarProv;
    private javax.swing.JButton btnRegProd;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    public static javax.swing.JTable tabla_prov;
    private javax.swing.JTextField txt_busdesc;
    // End of variables declaration//GEN-END:variables
}
