/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Interfaz;

import Modelo.SqlUsuarios;
import Modelo.usuarios;
import java.util.List;
import javax.swing.JOptionPane;
import javax.swing.JTable;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableColumnModel;

/**
 *
 * @author DELL
 */
public final class Usuarios extends javax.swing.JFrame {
ModificarUsuario frmodificar;
public static Registro frregistro;
SqlUsuarios usuario = new SqlUsuarios();
usuarios usu = new usuarios();
    /**
     * Creates new form Proveedor
     */
    public Usuarios() {
        initComponents();
         setLocationRelativeTo(null);
         tablaUsuario();
         propiedadesTabla();
         
//if(JFrame){}
//    }
//public void cerrar(){
//try{
//addWindowListener}
//catch(Exception e){
//    System.out.println(e);
//}
}
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        btnRegUsuario = new javax.swing.JButton();
        btnEliminarProv = new javax.swing.JButton();
        btnModificarProv = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        txt_bus = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        tabla_usu = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setBackground(new java.awt.Color(33, 45, 62));
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosing(java.awt.event.WindowEvent evt) {
                formWindowClosing(evt);
            }
        });

        jPanel1.setBackground(new java.awt.Color(33, 45, 62));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btnRegUsuario.setBackground(new java.awt.Color(33, 45, 62));
        btnRegUsuario.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btnRegUsuario.setForeground(new java.awt.Color(255, 255, 255));
        btnRegUsuario.setText("Registrar Usuario");
        btnRegUsuario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRegUsuarioActionPerformed(evt);
            }
        });
        jPanel1.add(btnRegUsuario, new org.netbeans.lib.awtextra.AbsoluteConstraints(21, 24, 160, 56));

        btnEliminarProv.setBackground(new java.awt.Color(33, 45, 62));
        btnEliminarProv.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btnEliminarProv.setForeground(new java.awt.Color(255, 255, 255));
        btnEliminarProv.setText("Eliminar Usuario");
        btnEliminarProv.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEliminarProvActionPerformed(evt);
            }
        });
        jPanel1.add(btnEliminarProv, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 220, 162, 56));

        btnModificarProv.setBackground(new java.awt.Color(33, 45, 62));
        btnModificarProv.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btnModificarProv.setForeground(new java.awt.Color(255, 255, 255));
        btnModificarProv.setText("Modificar Usuario");
        btnModificarProv.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnModificarProvActionPerformed(evt);
            }
        });
        jPanel1.add(btnModificarProv, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 120, 161, 56));

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Buscar usuario:");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 31, -1, -1));
        jPanel1.add(txt_bus, new org.netbeans.lib.awtextra.AbsoluteConstraints(323, 26, 268, -1));

        tabla_usu.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {

            }
        ));
        tabla_usu.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tabla_usuMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tabla_usu);

        jPanel1.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 60, 710, 430));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 920, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnRegUsuarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRegUsuarioActionPerformed
        if(frregistro== null)
        {
        frregistro= new Registro();
        frregistro.setVisible(true);
        }
        
    }//GEN-LAST:event_btnRegUsuarioActionPerformed

    private void btnEliminarProvActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEliminarProvActionPerformed
        // TODO add your handling code here:
        int fila= tabla_usu.getSelectedRow();
        int id =(int) tabla_usu.getValueAt(fila, 0);
        DefaultTableModel Tabla = new DefaultTableModel();
        try {
            if(fila<0){
            JOptionPane.showMessageDialog(this, "Seleccione alguna fila");
           
            }else {
                 usu.setId(id);
                if(JOptionPane.showConfirmDialog(this, "¿Eliminar el registro?", "",
                        JOptionPane.OK_CANCEL_OPTION)==JOptionPane.OK_OPTION){
                if(usuario.eliminarUsuario(usu)){
                
                JOptionPane.showMessageDialog(this, "Eliminado correctamente", "Información", JOptionPane.OK_OPTION);
                Tabla.removeRow(id);
                }else{
                JOptionPane.showMessageDialog(this, "Error al eliminar", "Información", JOptionPane.OK_CANCEL_OPTION);
                }
                }
            }
            JOptionPane.showMessageDialog(null, "Error al eliminar");
            
     
        }catch (Exception e){
        e.printStackTrace();
        }
    }//GEN-LAST:event_btnEliminarProvActionPerformed

    private void btnModificarProvActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnModificarProvActionPerformed
       if(frmodificar== null){
       frmodificar= new ModificarUsuario();
       frmodificar.setVisible(true);
       }



    }//GEN-LAST:event_btnModificarProvActionPerformed

    private void tabla_usuMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tabla_usuMouseClicked
 
        int fila =tabla_usu.getSelectedRow();
        ModificarUsuario.txt_cod.setText(String.valueOf(tabla_usu.getValueAt(fila, 0)));
        ModificarUsuario.txtUsuario.setText(String.valueOf(tabla_usu.getValueAt(fila, 1)));
        ModificarUsuario.txtNombre.setText(String.valueOf(tabla_usu.getValueAt(fila, 2)));
        ModificarUsuario.txtCorreo.setText(String.valueOf(tabla_usu.getValueAt(fila, 3)));
        ModificarUsuario.combo_tipo.setSelectedItem(String.valueOf(tabla_usu.getValueAt(fila, 4)));
        
        
    }//GEN-LAST:event_tabla_usuMouseClicked

    private void formWindowClosing(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosing
        // TODO add your handling code here:
        Menu.frusuarios=null;
    }//GEN-LAST:event_formWindowClosing

    
    
    public void tablaUsuario(){
    String [] columnas ={"ID","USUARIO","NOMBRE","CORREO","TIPO"};
    Object[] obj= new Object[5];
    DefaultTableModel Tabla = new DefaultTableModel(null, columnas);
    List ls;
    try{
    ls= usuario.mostrarUsuarios();
    for (int i=0;i<ls.size(); i++){
        usu = (usuarios) ls.get(i);
        obj[0] = usu.getId();
        obj[1] = usu.getUsuario();
        obj[2] = usu.getNombre();
        obj[3] = usu.getCorreo();
        obj[4] = usu.getNombre_tipo();    
        Tabla.addRow(obj);
    }
    tabla_usu.setModel(Tabla);
   }catch (Exception e){
 //  e.printStackTrace();
   System.out.println(e);
   }
    }
    
    public void propiedadesTabla(){
             tabla_usu.setAutoResizeMode(JTable.AUTO_RESIZE_OFF);
         TableColumnModel columnModel = tabla_usu.getColumnModel();
         columnModel.getColumn(0).setPreferredWidth(50);
         columnModel.getColumn(1).setPreferredWidth(150);
         columnModel.getColumn(2).setPreferredWidth(200);
         columnModel.getColumn(3).setPreferredWidth(200);
         columnModel.getColumn(4).setPreferredWidth(200);
    }
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Usuarios.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Usuarios.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Usuarios.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Usuarios.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Usuarios().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnEliminarProv;
    public static javax.swing.JButton btnModificarProv;
    private javax.swing.JButton btnRegUsuario;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tabla_usu;
    private javax.swing.JTextField txt_bus;
    // End of variables declaration//GEN-END:variables
}
